version: '3.7'

services:
  app:
    image: LotteryMinerDashboard-linux
    build: .
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /home/umbrel/umbrel/app-data/dashboard-data/data:/app/data
