version: '3.7'

services:
  app:
    image: AATEMinerDashboard-windows
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "33333:33333/udp"
    volumes:
      - ./data:/app/data
