version: '3.7'

services:
  app:
    image: AATEMinerDashboard
    restart: unless-stopped
    #network_mode: "host" #uncomment this if your running in a vm, otherwise the container will not listin on the proper subnet.
    ports:
      - "3000:3000/tcp" #dashboard port
      - "33333:33333/udp" #udp port for miner discovery
    volumes:
      - ./data:/app/data
      #- /home/umbrel/umbrel/app-data/dashboard-data/data:/app/data #only for use in a vm.
